export const QUERY_RESPONSE_KEY_ERROR = 'QUERY_RESPONSE_KEY_ERROR';
export const QUERY_RESPONSE_KEY_RESULT = 'QUERY_RESPONSE_KEY_RESULT';
export const QUERY_RESPONSE_KEY_SUCCESS = 'QUERY_RESPONSE_KEY_SUCCESS';
