export const QUERY_PARAM_DATABASE = 'd';
export const QUERY_PARAM_PAGE_CURSOR_ID_REQUEST = 'i';
export const QUERY_PARAM_PAGE_CURSOR_TYPE_REQUEST = 'c';

export const QUERY_VALUE_PAGE_CURSOR_TYPE_ALL = 'a';
export const QUERY_VALUE_PAGE_CURSOR_TYPE_DEFAULT = 'd';
export const QUERY_VALUE_PAGE_CURSOR_TYPE_SPECIFIC = 's';

export const QUERY_PARAM_INCLUDE_RELATIONSHIPS = 'r';

export const QUERY_PARAM_RESULT_COUNT = 'n';
export const QUERY_VALUE_RESULT_COUNT_ALL = 'a';
export const QUERY_PARAM_PRIMARY_TITLE_PROPERTY = 'p';