export const QUERY_RESPONSE_KEY_SUCCESS = 'QUERY_RESPONSE_KEY_SUCCESS';
export const QUERY_RESPONSE_KEY_ERROR = 'QUERY_RESPONSE_KEY_ERROR';
export const QUERY_RESPONSE_KEY_RESULT = 'QUERY_RESPONSE_KEY_RESULT';

//
// MOVE ALL OF THESE AND RENAME TO BLOCKS
//
export const QUERY_RESPONSE_KEY_PRIMARY_DATABASE = 'QUERY_RESPONSE_KEY_PRIMARY_DATABASE';
export const QUERY_RESPONSE_KEY_RELATION_DATABASES = 'QUERY_RESPONSE_KEY_RELATION_DATABASES';
export const QUERY_RESPONSE_KEY_DATABASE_ID = 'QUERY_RESPONSE_KEY_DATABASE_ID';
export const QUERY_RESPONSE_KEY_DATABASE_TITLE = 'QUERY_RESPONSE_KEY_DATABASE_TITLE';
export const QUERY_RESPONSE_KEY_PARENT_TITLE = 'QUERY_RESPONSE_KEY_PARENT_TITLE';
export const QUERY_RESPONSE_KEY_PARENT_ID = 'QUERY_RESPONSE_KEY_PARENT_ID';
export const QUERY_RESPONSE_KEY_PARENT_TYPE = 'QUERY_RESPONSE_KEY_PARENT_TYPE';
export const QUERY_RESPONSE_KEY_BLOCKS = 'QUERY_RESPONSE_KEY_BLOCKS';
export const QUERY_RESPONSE_KEY_COLUMN_LISTS = 'QUERY_RESPONSE_KEY_COLUMN_LISTS';
export const QUERY_RESPONSE_KEY_CURSOR_DATA = 'QUERY_RESPONSE_KEY_CURSOR_DATA';
export const QUERY_RESPONSE_KEY_ICON = 'QUERY_RESPONSE_KEY_ICON';
export const QUERY_RESPONSE_KEY_COVER = 'QUERY_RESPONSE_KEY_COVER';
export const QUERY_RESPONSE_KEY_PAGE_DATA = 'QUERY_RESPONSE_KEY_PAGE_DATA';

export const QUERY_RESPONSE_KEY_START_DATE = 'QUERY_RESPONSE_KEY_START_DATE';
export const QUERY_RESPONSE_KEY_END_DATE = 'QUERY_RESPONSE_KEY_END_DATE';
export const QUERY_RESPONSE_TIME_ZONE = 'QUERY_RESPONSE_TIME_ZONE';

export const QUERY_RESPONSE_KEY_DATA_TYPE = 'TYPE';
export const QUERY_RESPONSE_KEY_DATA_VALUE = 'VALUE';
export const QUERY_RESPONSE_KEY_DATA_KEY = 'KEY';
export const QUERY_RESPONSE_KEY_DATA_PROPERTIES = 'PROPERTIES';
export const QUERY_RESPONSE_KEY_DATA_METADATA = 'METADATA';

export const QUERY_RESPONSE_KEY_BLOCK_ID = 'BLOCK_ID';
export const QUERY_RESPONSE_KEY_PAGE_ID = 'PAGE_ID';