export const SEARCH_PARAM_DATABASE = 'd';
export const SEARCH_PARAM_BLOCKS_REQUEST = 'b';
export const SEARCH_PARAM_RELATIONS_REQUEST = 'r';
export const SEARCH_PARAM_PAGE_CURSOR_TYPE_REQUEST = 'c';
export const SEARCH_PARAM_PAGE_CURSOR_ID_REQUEST = 'i';

export const SEARCH_VALUE_PAGE_CURSOR_TYPE_ALL = 'a';
export const SEARCH_VALUE_PAGE_CURSOR_TYPE_SPECIFIC = 's';
export const SEARCH_VALUE_PAGE_CURSOR_TYPE_DEFAULT = 'd';